{{- if include "banking-web-application.createSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "banking-web-application.secretName" . }}
  labels:
    {{- include "banking-web-application.labels" . | nindent 4 }}
type: Opaque
stringData:
  legacy-api-key: {{ .Values.legacy.apiKey | quote }}
{{- end }}
