{{- if include "legacy-service.createSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "legacy-service.secretName" . }}
  labels:
    {{- include "legacy-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.postgres.databaseUrl }}
  {{ .Values.postgres.existingSecretKey }}: {{ .Values.postgres.databaseUrl | quote }}
  {{- end }}
  {{- if .Values.apiKey }}
  api-key: {{ .Values.apiKey | quote }}
  {{- end }}
{{- end }}
